//
//  Header.h
//  QianSen
//
//  Created by Kevin on 16/4/11.
//  Copyright © 2016年 Kevin. All rights reserved.
//

#ifndef Header_h
#define Header_h

#define CC_TASK_EROLLNEWUSER_DESCPRITION @"CC_TASK_DESCPRITION_EROLLNEWUSER"
#define CC_TASK_EROLLNEWUSER_NOTIFICATION @"CC_TASK_EROLLNEWUSER_NOTIFICATION"

#define CC_TASK_LOGIN_DESCPRITION @"CC_TASK_LOGININ_DESCPRITION"
#define CC_TASK_LOGIN_NOTIFICATION @"CC_TASK_LOGININ_NOTIFICATION"

#define CC_TASK_UPLOADHEADIMAGE_DESCPRITION @"CC_TASK_UPLOADHEADIMAGE_DESCPRITION"
#define CC_TASK_UPLOADHEADIMAGE_NOTIFICATION @"CC_TASK_UPLOADHEADIMAGE_NOTIFICATION"

#define CC_TASK_SEARCHACCOUNT_DESCPRITION @"CC_TASK_SEARCHACCOUNT_DESCPRITION"
#define CC_TASK_SEARCHACCOUNT_NOTIFICATION @"CC_TASK_SEARCHACCOUNT_NOTIFICATION"

#define CC_TASK_ADDFRIEND_DESCPRITION @"CC_TASK_ADDFRIEND_DESCPRITION"
#define CC_TASK_ADDFRIEND_NOTIFICATION @"CC_TASK_ADDFRIEND_NOTIFICATION"

#define CC_TASK_GETFRIENDSLIST_DESCPRITION @"CC_TASK_GETFRIENDSLIST_DESCPRITION"
#define CC_TASK_GETFRIENDSLIST_NOTIFICATION @"CC_TASK_GETFRIENDSLIST_NOTIFICATION"

#endif /* Header_h */
